development:
  encoding: utf8
  adapter: mysql2
  host: localhost
  database: PIS_development
  username: root
  password: 
  pool: 5

test:
  encoding: utf8
  adapter: mysql2
  database: PIS_test
  username: postgres
  password: sa
  pool: 5

production:
  encoding: unicode
  adapter: postgresql
  database: PIS_production
  username: postgres
  password: sa
  pool: 5