default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: PIS_development
  username: postgres
  password: sa

test:
  <<: *default
  database: PIS_test
  username: postgres
  password: sa

production:
  <<: *default
  database: PIS_production
  username: postgres
  password: 